TimePro/Models/Note.cs
namespace TimePro.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("Note")]
    public partial class Note
    {
        public int NoteID { get; set; }

        [Required]
        public string NoteTitle { get; set; }

        public string NoteLabel { get; set; }

        public int? UserID { get; set; }

        public int? NoteTime { get; set; }

        [Column(TypeName = "ntext")]
        public string NoteContent { get; set; }

        public int? NoteGetNumber { get; set; }

        public DateTime? NoteCreateTime { get; set; }

        public int? NoteFlag { get; set; }

        public DateTime? NoteFinishTime { get; set; }

        public virtual User User { get; set; }

        public virtual User User1 { get; set; }
    }
}

TimePro/Controllers/ChatsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TimePro.Models;

namespace TimePro.Controllers
{
    public class ChatsController : Controller
    {
        private TimeProContext db = new TimeProContext();

        // GET: Chats
        public ActionResult ChatsIndex()
        {
            String usercode = Session["username"].ToString();
            int nid = 0;
            foreach (var item in db.User.ToList<User>())
            {
                var Result = from a in db.User
                             where a.UserCode == usercode
                             select a;
                foreach (var result in Result)
                {
                    nid = result.UserID;
                }
            }
            User user = db.User.Find(nid);


            var chat = db.Chat.Include(c => c.User).Include(c => c.User1);
            ViewModel model = new ViewModel();
            model.UserModel = user;
            model.ChatModel = chat.ToList();
            return View(model);
        }

        // GET: Chats/Details/5
        public ActionResult ChatsDetails(int? id)
        {
            String usercode = Session["username"].ToString();
            int nid = 0;
            foreach (var item in db.User.ToList<User>())
            {
                var Result = from a in db.User
                             where a.UserCode == usercode
                             select a;
                foreach (var result in Result)
                {
                    nid = result.UserID;
                }
            }
            User user = db.User.Find(nid);

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Chat chat = db.Chat.Find(id);
            if (chat == null)
            {
                return HttpNotFound();
            }

            Chat ChatModel = db.Chat.Find(id);
            ChatModel.ChatFlag = 1;
            db.Entry(ChatModel).State = EntityState.Modified;
            db.SaveChanges();

            ViewModel1 model = new ViewModel1();
            model.UserModel = user;
            model.ChatModel = chat;
            return View(model);
        }

        public ActionResult ChatsDetailsFrom(int? id)
        {
            String usercode = Session["username"].ToString();
            int nid = 0;
            foreach (var item in db.User.ToList<User>())
            {
                var Result = from a in db.User
                             where a.UserCode == usercode
                             select a;
                foreach (var result in Result)
                {
                    nid = result.UserID;
                }
            }
            User user = db.User.Find(nid);

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Chat chat = db.Chat.Find(id);
            if (chat == null)
            {
                return HttpNotFound();
            }

            ViewModel1 model = new ViewModel1();
            model.UserModel = user;
            model.ChatModel = chat;
            return View(model);
        }

        public ActionResult ChatsDetailsTo(int? id)
        {
            String usercode = Session["username"].ToString();
            int nid = 0;
            foreach (var item in db.User.ToList<User>())
            {
                var Result = from a in db.User
                             where a.UserCode == usercode
                             select a;
                foreach (var result in Result)
                {
                    nid = result.UserID;
                }
            }
            User user = db.User.Find(nid);

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Chat chat = db.Chat.Find(id);
            if (chat == null)
            {
                return HttpNotFound();
            }

            Chat ChatModel = db.Chat.Find(id);
            ChatModel.ChatFlag = 1;
            db.Entry(ChatModel).State = EntityState.Modified;
            db.SaveChanges();

            ViewModel1 model = new ViewModel1();
            model.UserModel = user;
            model.ChatModel = chat;
            return View(model);
        }

        public ActionResult ChatsCreate(ViewModel1 model)
        {
            model.ChatModel.ChatFrom = model.UserModel.UserID;
            model.ChatModel.ChatTo = (int)model.NoteModel.UserID;
            model.ChatModel.ChatFlag = 0;
            model.ChatModel.ChatTime = System.DateTime.Now;
            db.Chat.Add(model.ChatModel);
            db.SaveChanges();
            return Content("<script >alert('已成功提交！');history.go(-1)</script >", "text/html");
        }

        public ActionResult ChatsCreateChat(ViewModel1 model)
        {
            model.ChatModel.ChatTo = model.ChatModel.ChatFrom;
            model.ChatModel.ChatFrom = model.UserModel.UserID;
            model.ChatModel.ChatFlag = 0;
            model.ChatModel.ChatTime = System.DateTime.Now;
            db.Chat.Add(model.ChatModel);
            db.SaveChanges();
            return Content("<script >alert('已成功提交！');history.go(-1)</script >", "text/html");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TimePro/Controllers/NotesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TimePro.Models;

namespace TimePro.Controllers
{
    public class NotesController : Controller
    {
        private TimeProContext db = new TimeProContext();

        // GET: Notes
        [Filter.Filter.LoginFilter]
        public ActionResult NotesIndex()
        {
            String usercode = Session["username"].ToString();
            int nid = 0;
            foreach (var item in db.User.ToList<User>())
            {
                var Result = from a in db.User
                             where a.UserCode == usercode
                             select a;
                foreach (var result in Result)
                {
                    nid = result.UserID;
                }
            }
            User user = db.User.Find(nid);
            var note = from b in db.Note.Include(n => n.User) where b.UserID == user.UserID select b;
            ViewModel model = new ViewModel();
            model.UserModel = user;
            model.NoteModel = note.ToList();
            return View(model);
        }

        [Filter.Filter.LoginFilter]
        public ActionResult NotesAll()
        {
            String usercode = Session["username"].ToString();
            int nid = 0;
            foreach (var item in db.User.ToList<User>())
            {
                var Result = from a in db.User
                             where a.UserCode == usercode
                             select a;
                foreach (var result in Result)
                {
                    nid = result.UserID;
                }
            }
            User user = db.User.Find(nid);
            var note = from b in db.Note.Include(n => n.User) where b.UserID != user.UserID && b.NoteFlag == 0 orderby b.NoteCreateTime descending select b;
            ViewModel model = new ViewModel();
            model.UserModel = user;
            model.NoteModel = note.ToList();
            return View(model);
        }

        // GET: Notes/Details/5
        [Filter.Filter.LoginFilter]
        public ActionResult NotesDetails(int? id)
        {
            String usercode = Session["username"].ToString();
            int nid = 0;
            foreach (var item in db.User.ToList<User>())
            {
                var Result = from a in db.User
                             where a.UserCode == usercode
                             select a;
                foreach (var result in Result)
                {
                    nid = result.UserID;
                }
            }
            User user = db.User.Find(nid);

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Note note = db.Note.Find(id);
            if (note == null)
            {
                return HttpNotFound();
            }
            ViewModel1 model = new ViewModel1();
            model.UserModel = user;
            model.NoteModel = note;
            return View(model);
        }


        // GET: Notes/Create
        [Filter.Filter.LoginFilter]
        public ActionResult NotesCreate()
        {
            String usercode = Session["username"].ToString();
            int id = 0;
            foreach (var item in db.User.ToList<User>())
            {
                var Result = from a in db.User
                             where a.UserCode == usercode
                             select a;
                foreach (var result in Result)
                {
                    id = result.UserID;
                }
            }
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.User.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            if(user.UserTime ==0)
            {
                return Content("<script >alert('账号时间不足，不能创建项目！');history.go(-1)</script >", "text/html");
            }
            else
            {
                Note note = new Note();
                ViewModel1 model = new ViewModel1();
                model.UserModel = user;
                model.NoteModel = note;
                return View(model);
            }
            
        }

        // POST: Notes/Create
        // 为了防止“过多发布”攻击，请启用要绑定到的特定属性，有关 
        // 详细信息，请参阅 http://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateInput(false)]
        [ValidateAntiForgeryToken]
        [Filter.Filter.LoginFilter]
        public ActionResult NotesCreate(ViewModel1 note)
        {
            String usercode = Session["username"].ToString();
            int id = 0;
            foreach (var item in db.User.ToList<User>())
            {
                var Result = from a in db.User
                             where a.UserCode == usercode
                             select a;
                foreach (var result in Result)
                {
                    id = result.UserID;
                }
            }
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.User.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            if(note.NoteModel.NoteTime > user.UserTime)
            {
                return Content("<script >alert('账号时间小于所需要的时间，不能创建项目！');history.go(-1)</script >", "text/html");
            }
            else
            {
                note.NoteModel.NoteFlag = 0;
                note.NoteModel.UserID = user.UserID;
                note.NoteModel.NoteCreateTime = System.DateTime.Now;
                if (ModelState.IsValid)
                {
                    db.Note.Add(note.NoteModel);
                    db.SaveChanges();
                    return RedirectToAction("../Notes/NotesIndex");
                }
            }
            

            ViewBag.UserID = new SelectList(db.User, "UserID", "UserCode", note.NoteModel.UserID);
            ViewModel1 model = new ViewModel1();
            model.UserModel = user;
            model.NoteModel = note.NoteModel;
            return View(model);
        }

        // GET: Notes/Edit/5
        [ValidateInput(false)]
        [Filter.Filter.LoginFilter]
        public ActionResult NotesEdit(int? id)
        {
            String usercode = Session["username"].ToString();
            int nid = 0;
            foreach (var item in db.User.ToList<User>())
            {
                var Result = from a in db.User
                             where a.UserCode == usercode
                             select a;
                foreach (var result in Result)
                {
                    nid = result.UserID;
                }
            }
            User user = db.User.Find(nid);

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Note note = db.Note.Find(id);
            if (note == null)
            {
                return HttpNotFound();
            }
            ViewBag.UserID = new SelectList(db.User, "UserID", "UserCode", note.UserID);
            ViewModel1 model = new ViewModel1();
            model.UserModel = user;
            model.NoteModel = note;
            return View(model);
        }

        // POST: Notes/Edit/5
        // 为了防止“过多发布”攻击，请启用要绑定到的特定属性，有关 
        // 详细信息，请参阅 http://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateInput(false)]
        [ValidateAntiForgeryToken]
        [Filter.Filter.LoginFilter]
        public ActionResult NotesEdit(ViewModel1 note)
        {
            String usercode = Session["username"].ToString();
            int nid = 0;
            foreach (var item in db.User.ToList<User>())
            {
                var Result = from a in db.User
                             where a.UserCode == usercode
                             select a;
                foreach (var result in Result)
                {
                    nid = result.UserID;
                }
            }
            User user = db.User.Find(nid);

            Note NoteModel = db.Note.Find(note.NoteModel.NoteID);
            NoteModel.NoteTitle = note.NoteModel.NoteTitle;
            NoteModel.NoteLabel = note.NoteModel.NoteLabel;
            NoteModel.NoteTime = note.NoteModel.NoteTime;
            NoteModel.NoteContent = note.NoteModel.NoteContent;

            if (ModelState.IsValid)
            {
                db.Entry(NoteModel).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("../Notes/NotesIndex");
            }
            ViewBag.UserID = new SelectList(db.User, "UserID", "UserCode", note.UserModel.UserID);
            return View(note.NoteModel);
        }

        // GET: Notes/Delete/5
        [Filter.Filter.LoginFilter]
        public ActionResult NotesDelete(int? id)
        {
            String usercode = Session["username"].ToString();
            int nid = 0;
            foreach (var item in db.User.ToList<User>())
            {
                var Result = from a in db.User
                             where a.UserCode == usercode
                             select a;
                foreach (var result in Result)
                {
                    nid = result.UserID;
                }
            }
            User user = db.User.Find(nid);

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Note note = db.Note.Find(id);
            if (note == null)
            {
                return HttpNotFound();
            }

TimePro/Views/Notes/NotesAllDetails.cshtml
@model TimePro.Models.ViewModel1

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<script type="text/javascript" src="http://www.francescomalagrino.com/BootstrapPageGenerator/3/js/jquery-2.0.0.min.js"></script>
<script type="text/javascript" src="http://www.francescomalagrino.com/BootstrapPageGenerator/3/js/jquery-ui"></script>
<link href="http://www.francescomalagrino.com/BootstrapPageGenerator/3/css/bootstrap-combined.min.css" rel="chrome-webstore-item" media="screen">
<script type="text/javascript" src="http://www.francescomalagrino.com/BootstrapPageGenerator/3/js/bootstrap.min.js"></script>
@using (Html.BeginForm("NotesAllDetails", "Notes", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="row-fluid">
        <br /><br />
        <div class="col-md-12">
            <div class="row-fluid">
                <div class="col-md-2">
                    @if (Model.UserModel != null)
                {
                    if (Model.UserModel.UserPhoto != null)
                    {
                            <img width="140" height="140" class="img-circle" src=" @Url.Action("GetImage", "Users", new { Model.UserModel.UserID }) ">
                        }
                        else
                        {
                            <img alt="140x140" src="~/Image/user.jpg" class="img-circle" />
                        }
                    }
                    <br /><br />
                    <blockquote>
                        <ul class="nav nav-list">
                            <li class="nav-header">
                                <strong>我的</strong>
                            </li>
                            <li class="active">
                                <a href="~/Users/UsersIndex">首页</a>
                            </li>
                            <li>
                                <a href="~/Notes/NotesIndex">时间</a>
                            </li>
                            <li class="nav-header">
                                <strong>功能</strong>
                            </li>
                            <li>
                                <a href="~/Chats/ChatsIndex">通知</a>
                            </li>
                            <li>
                                <a href="~/Users/UsersDetails">资料</a>
                            </li>
                        </ul>
                    </blockquote>
                </div>
                <br />
                <div class="col-md-10">
                    <a href="~/Notes/NotesCreate" class="btn btn-large btn-success btn-default">添加项目</a>
                    <br /><br />
                    <ul class="nav nav-tabs">
                        <li class="active">
                            <a href="#">可参与的项目详情</a>
                        </li>
                        <li>
                            <a href="~/Notes/NotesAll">所有可参与的项目</a>
                        </li>
                        <li>
                            <a href="~/Notes/NotesIndex">我的项目</a>
                        </li>
                        <li>
                            <a href="~/Notes/NotesIng">正在进行的项目</a>
                        </li>
                        <li>
                            <a href="~/Notes/NotesFinish">已完成的项目</a>
                        </li>
                    </ul>
                    <br /><br />

                    <div class="row-fluid">
                        <div class="form-horizontal">

                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            @Html.HiddenFor(model => model.NoteModel.NoteID)

                            <div class="form-group">
                                @Html.LabelFor(model => model.NoteModel.NoteTitle, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.NoteModel.NoteTitle, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.NoteModel.NoteTitle, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.NoteModel.NoteLabel, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.NoteModel.NoteLabel, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.NoteModel.NoteLabel, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.NoteModel.NoteTime, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.NoteModel.NoteTime, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.NoteModel.NoteTime, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.NoteModel.NoteContent, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.Raw(@HttpUtility.HtmlDecode(@Model.NoteModel.NoteContent))
                                </div>
                            </div>

                        </div>
                        <div class="form-group">
                            <div class="col-md-offset-1 col-md-10">
                                <input type="submit" value="确认参与此项目" class="btn btn-large btn-primary btn-default" />
                                <button class="btn btn-primary btn-large" data-toggle="modal" data-target="#myModal">留言</button>
                                <a href="~/Notes/NotesAll" class="btn btn-large btn-primary btn-default">返回</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

@using (Html.BeginForm("ChatsCreate", "Chats", FormMethod.Post))
{   @Html.AntiForgeryToken()
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog"
         aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">

                <div class="modal-header">
                    <button type="button" class="close"
                            data-dismiss="modal" aria-hidden="true">
                        &times;
                    </button>
                    <h4 class="modal-title" id="myModalLabel">
                        留言
                    </h4>
                </div>
                
                <div class="modal-body">
                    <div class="form-horizontal">
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <div class="form-group">
                            @Html.LabelFor(model => model.ChatModel.ChatFrom, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => Model.UserModel.UserID, new { @readOnly = "readOnly" })
                                @Html.ValidationMessageFor(model => model.ChatModel.ChatFrom, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.ChatModel.ChatTo, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => Model.NoteModel.UserID, new { @readOnly = "readOnly" })
                                @Html.ValidationMessageFor(model => model.ChatModel.ChatTo, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.ChatModel.ChatContent, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.TextAreaFor(model => model.ChatModel.ChatContent, new { id = "text" })
                            </div>
                        </div>

                    </div>
                </div>

                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
                    <input type="submit" value="提交" class="btn btn-large btn-primary btn-default" />
                </div>

            </div>
        </div>
    </div>


}

TimePro/Views/Notes/NotesDelete.cshtml
@model TimePro.Models.ViewModel1

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<script type="text/javascript" src="http://www.francescomalagrino.com/BootstrapPageGenerator/3/js/jquery-2.0.0.min.js"></script>
<script type="text/javascript" src="http://www.francescomalagrino.com/BootstrapPageGenerator/3/js/jquery-ui"></script>
<link href="http://www.francescomalagrino.com/BootstrapPageGenerator/3/css/bootstrap-combined.min.css" rel="chrome-webstore-item" media="screen">
<script type="text/javascript" src="http://www.francescomalagrino.com/BootstrapPageGenerator/3/js/bootstrap.min.js"></script>
@using (Html.BeginForm("DeleteConfirmed", "Notes", FormMethod.Post))
{
    @Html.AntiForgeryToken()
<div class="row-fluid">
    <br /><br />
    <div class="col-md-12">
        <div class="row-fluid">
            <div class="col-md-2">
                @if (Model.UserModel.UserPhoto != null)
                {
                    <img width="140" height="140" class="img-circle" src=" @Url.Action("GetImage", "Users", new { Model.UserModel.UserID }) ">
                }
                else {
                    <img alt="140x140" src="~/Image/user.jpg" class="img-circle" />
                }
                <br /><br />
                <blockquote>
                    <ul class="nav nav-list">
                        <li class="nav-header">
                            <strong>我的</strong>
                        </li>
                        <li class="active">
                            <a href="~/Users/UsersIndex">首页</a>
                        </li>
                        <li>
                            <a href="~/Notes/NotesIndex">时间</a>
                        </li>
                        <li class="nav-header">
                            <strong>功能</strong>
                        </li>
                        <li>
                            <a href="~/Chats/ChatsIndex">通知</a>
                        </li>
                        <li>
                            <a href="~/Users/UsersDetails">资料</a>
                        </li>
                    </ul>
                </blockquote>
            </div>
            <br />
            <div class="col-md-10">
                <a href="~/Notes/NotesCreate" class="btn btn-large btn-success btn-default">添加项目</a>
                <br /><br />
                <ul class="nav nav-tabs">
                    <li class="active">
                        <a href="#">删除项目</a>
                    </li>
                    <li>
                        <a href="~/Notes/NotesAll">所有可参与的项目</a>
                    </li>
                    <li>
                        <a href="~/Notes/NotesIndex">我的项目</a>
                    </li>
                    <li>
                        <a href="~/Notes/NotesIng">正在进行的项目</a>
                    </li>
                    <li>
                        <a href="~/Notes/NotesFinish">已完成的项目</a>
                    </li>
                </ul>
                <br /><br />
                <div class="row-fluid">
                    <div class="col-md-12">
                        <div class="form-horizontal">

                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            @Html.HiddenFor(model => model.NoteModel.NoteID)

                            <div class="form-group">
                                @Html.LabelFor(model => model.NoteModel.NoteTitle, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.DisplayFor(model => model.NoteModel.NoteTitle, new { htmlAttributes = new { @class = "form-control" } })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.NoteModel.NoteLabel, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.DisplayFor(model => model.NoteModel.NoteLabel, new { htmlAttributes = new { @class = "form-control" } })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.NoteModel.NoteTime, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.DisplayFor(model => model.NoteModel.NoteTime, new { htmlAttributes = new { @class = "form-control" } })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.NoteModel.NoteContent, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.Raw(@HttpUtility.HtmlDecode(@Model.NoteModel.NoteContent))
                                </div>
                            </div>

                        </div>

                            <div class="form-actions no-color">
                                <input type="submit" value="确定删除" class="btn btn-large btn-primary btn-default"  />
                            </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
}